import Foundation

// swiftlint:disable file_length
// swiftlint:disable type_body_length
public typealias MAEvent = MotorwayAnalytics.Event
public typealias MAEventType = MotorwayAnalytics.EventType
public typealias MAParams = MotorwayAnalytics.Params
public typealias MASource = MotorwayAnalytics.Source

public struct MotorwayAnalytics {

    public enum Screen: String {
        case notificationBanner = "notification-banner"

        public var value: String {
            return self.rawValue
        }
    }
}

extension MotorwayAnalytics {
    public enum Event {
        case getStarted
        case updatePhotoData
        case notificationBanner
        case motorwaySlideInGuide
        case motorwayCameraControlsOrientation(orientation: Int)
        case usedMotorwayBefore
        case signIn
        case openPrivacyPolicyTermsUrl
        case privacyPolicyTerms
        case dismiss
        case selectedLibraryPhotos
        case coreDataDeletionError
        case slideInGuideImageTapped
        case slideInGuideImageFetchRequest
        case exit
        case usePhoto
        case retakePhoto
        case cameraCarExample
        case skipOptionalPhoto
        case takePhoto
        case cameraPermission(result: String)
        case sellerPhotoDataRetrieveFailed
        case cameraTapToFocus
        case mlCompositionFailed
        case motorwayCamera
        case motorwayCameraPreview
        case motorwayCameraRotateDevice
        case motorwayPhotosAppClipHome
        case motorwayPhotosAppClipWelcomeGuide
        case viewVehicleDetailsSummaryTapped
        case confirmPhotoEditTapped
        case coreDataThreadViolation
        case vehicleHome
        case confirmYourProfileClicked
        case highMileage
        case continueTapped
        case mileageLessThanLastMOT
        case valuationFetchFailed
        case valuationFailed
        case vehicleProfile
        case profileSummary
        case vehicleProfileSummaryConfirmTap
        case vehicleProfileLetsGetStarted
        case vehicleProfileProofOfPurchaseQuestion
        case vehicleProfileEquipmentQuestion
        case vehicleProfileSeatMaterialQuestion
        case vehicleProfileNumberOfKeysQuestion
        case vehicleProfileToolPackQuestion
        case vehicleProfileLockingWheelNutQuestion
        case vehicleProfileSmokingQuestion
        case vehicleProfileV5cLogbookQuestion
        case vehicleProfileLocationSearchQuestion
        case addressSuggestionsFailed
        case addressDetailsFailed
        case vehicleProfileLocationFormQuestion
        case updateSellerFailed
        case vehicleProfileOwnerQuestion
        case vehicleProfileOwnerTypeQuestion
        case vehicleProfileOwnerNameQuestion
        case vehicleProfilePrivatePlateQuestion
        case vehicleProfileKeepingThePlateQuestion
        case vehicleProfileKeepPrivatePlateLinkTap
        case vehicleProfileFinanceQuestion
        case vehicleProfileBatteryOwnershipQuestion
        case vehicleProfileChargingCablesQuestion
        case vehicleProfileProofOfPurchaseGuide
        case vehicleProfileNoProofOfPurchaseGuide
        case vehicleProfileProofOfPurchaseCallTap
        case vehicleProfileV5cLogBookGuide
        case vehicleProfileNoV5cLogbookGuide
        case vehicleCriteriaNotMetGuideView
        case vehicleProfileConfirmCriteriaTap
        case vehicleProfileV5CLogBookDVLALinkTap
        case vehicleProfileSeatMaterialGuide
        case vehicleProfileToolPackGuide
        case vehicleProfileLockingWheelNutGuide
        case vehicleProfileChargingCablesGuide
        case photoTips
        case deletePhoto
        case photoCategoryExteriorTips
        case photoCategoryInteriorTips
        case photoCategoryWheelTips
        case photoCategoryTyreTreadTips
        case photoTipTakeGoodPhotos
        case photoTipTidyAndClean
        case photoTipGoodLighting
        case photoTipVehicleSpace
        case photoRequirementsTips
        case vehicleCondition
        case takeMissingWheelPhotos
        case takeMissingTyrePhotos
        case conditionFailed
        case vehicleConditionCategory(condition: String)
        case vehicleConditionCategoryGallery(photoType: String)
        case retryPhotoUpload
        case vehicleConditionCategoryGalleryWheelDamage
        case vehicleConditionCategoryGalleryTyreDamage
        case vehicleConditionCategoryTyreDamage
        case noWheelDamage
        case noTyreDamage
        case hasWheelDamage
        case hasTyreDamage
        case vehicleConditionScratchesScuffsGuide
        case vehicleConditionDentsGuide
        case vehicleConditionPaintworkProblemsGuide
        case vehicleConditionWindscreenDamageGuide
        case vehicleConditionWarningLightsGuide
        case vehicleConditionWheelDamageGuide
        case vehicleConditionTyreDamageGuide
        case vehicleBodyDamageLocationChooser
        case vehicleServiceHistoryPhotos
        case photoPickerTapped
        case vehicleServiceHistoryInitialMenu
        case updateServiceHistoryFailed
        case tooManyVehicles
        case removeVehicleFailed
        case vehicleRemoved
        case priceEstimateExplanation
        case priceEstimateExplanationCallTap
        case whyHasMyPriceChangedPageCallButton
        case whyHasMyPriceChangedPageLoaded
        case confirmSheetView
        case confirmMyPricePageLoaded
        case confirmationModalPageLoaded
        case confirmProfile
        case confirmMyPriceClicked
        case confirmProfileWithIncompleteVehicleDetails
        case confirmProfileFailedToRefreshVehicleProfile
        case confirmProfileFailed
        case whyHasMyPriceChangedClicked
        case confirmVehicleSummary
        case confirmEditVehicleProfileQuestion
        case confirmEditDamagedWheels
        case confirmEditDamagedTyres
        case confirmEditDamageScratches
        case confirmEditDamageDents
        case confirmEditDamagePaintwork
        case confirmEditDamageMissingTrims
        case confirmEditDamageWindscreen
        case confirmEditDamageWarningLights
        case confirmEditServiceHistory
        case continueToConfirm
        case getSellerPrepFailed
        case getVehicleProfileFailed
        case authenticationTokenIsEmptyOrNull
        case authenticationResetToken
        case requestVerificationCodeFailed
        case signInByMobileCodeFailed
        case checkIdentityFailed
        case authenticateFailed
        case signInMobile
        case signInMobileNumberNotFound
        case signInResendVerificationCode
        case signInEnterVerificationCode
        case appClipSignInFailed
        case accountDoesNotExist
        case startSelling
        case startSellingFailed
        case checkVerificationCodeFailed
        case checkVerificationCodeSuccess
        case enterVrm
        case confirmVehicle
        case vrmSearch
        case vrmNotFound
        case vrmInvalid
        case vrmCheckFailed
        case checkEligibilityFailed
        case estimateValuationFailed
        case validMileageConfirmedEqualToEstimated
        case validMileageConfirmedEqualToLastMOT
        case validMileageConfirmedEqualToEstimatedAndLastMOT
        case validMileageConfirmedLessThanEstimated
        case validMileageConfirmedGreaterThanEstimated
        case validMileageEntered
        case ineligibleVehicle(reason: String)
        case enterFullName
        case enterEmail
        case enterMobileNumber
        case phoneNumberUpdateNeeded
        case enterVerificationCode
        case valuationTooManyVehicles
        case valuation
        case yourEstimatedPrice
        case profileCompleteCallTapped
        case nextSteps
        case dateFormattingFailed
        case deletePhotoTapped
        case viewPhotoAIAssistError
        case confirmVehicleWithAIAssistError
        case vehiclePhotoCardTapped
        case photoUploadSuccess
        case photoUploadFailed
        case selectedCameraDevice
        case editPhotoTapped
        case invalidUrl
        case remoteImageDownloadFailed
        case serviceHistoryCaptureTips
        case vehicleServiceHistory
        case priceConfirmationTerms
        case vehiclePhotosCategory(category: String)
        case serviceHistoryHelpDefinition
        case vehiclePhotos
        case motorwayPhotosAppClipLoading
        case findServiceHistoryHelp
        case noServiceHistory
        case vehicleList
        case photoAIAssistPollingTimedOut
        case remoteConfigFetchAndActivateFailed
        case remoteConfigListeningFailed
        case getPhotosFailed
        case updateVehicleProfileFailed
        case updateDamageMetadataFailed
        case getEnquiryTimelineFailed
        case createEnquiryFailed
        case valuateEnquiryFailed
        case appClipUrl
        case customDebug
        case malformedHTTPResponse
        case cachedPhotoMissing
        case unableToLoadCachedImage
        case deletePhotoFailed
        case photosToDownload
        case photosDownloaded
        case photoCorrectTapped
        case dynamicLinkProcessingFailed
        case vehicleEngineCheckTipsTapped
        case vehicleEngineCheckOpenTapped
        case vehicleEngineCheckSkipTapped
        case vehicleEngineCheckCameraOpened
        case vehicleEngineCheckRetakeTapped
        case vehicleEngineCheckUseVideoTapped
        case vehicleEngineCheckDeleteVideo
        case vehicleEngineCheckCameraDismissed
        case noVehicleMatchingVrm
        case noDealerEnquiryId
        case dealerEnquiryIdIsZero
        case fileDeletionError
        case userDetailsFailed
        case presignedUrlFailed
        case s3UploadFailed
        case s3UploadSuccess
        case noEnquiryId
        case apiResponseMissingEnquiryObject
        case apiResponseMissingDealerObject
        case apiResponseDealerEnquiryIdIsZero
        case enquiryProgressFailed
        case enquiryProgressOverall
        case enquiryProgressVehicleProfile
        case enquiryProgressPhotosExterior
        case enquiryProgressPhotosInterior
        case enquiryProgressPhotosWheels
        case enquiryProgressPhotosTyres
        case enquiryProgressCondition
        case enquiryProgressServiceHistory
        case getUserFailed

        public var value: String {
            switch self {
            case .getStarted:
                return "get-started"
            case .updatePhotoData:
                return "update-photo-data"
            case .notificationBanner:
                return "notification-banner"
            case .motorwaySlideInGuide:
                return "motorway-slide-in-guide"
            case .motorwayCameraControlsOrientation(let orientation):
                return "motorway-camera-controls-orientation-\(orientation)"
            case .usedMotorwayBefore:
                return "used-motorway-before"
            case .signIn:
                return "sign-in"
            case .openPrivacyPolicyTermsUrl:
                return "open-privacy-policy-terms-url"
            case .privacyPolicyTerms:
                return "privacy-policy-terms"
            case .dismiss:
                return "dismiss"
            case .selectedLibraryPhotos:
                return "selected-library-photos"
            case .coreDataDeletionError:
                return "coredata-deletion-error"
            case .slideInGuideImageTapped:
                return "slide-in-guide-image-tapped"
            case .slideInGuideImageFetchRequest:
                return "slide-in-guide-image-fetch-request"
            case .exit:
                return "exit"
            case .usePhoto:
                return "use-photo"
            case .retakePhoto:
                return "retake-photo"
            case .cameraCarExample:
                return "camera-car-example"
            case .skipOptionalPhoto:
                return "skip-optional-photo"
            case .takePhoto:
                return "take-photo"
            case .cameraPermission(let result):
                return "camera-permission-\(result)"
            case .sellerPhotoDataRetrieveFailed:
                return "seller-photo-data-retrieve-failed"
            case .cameraTapToFocus:
                return "camera-tap-to-focus"
            case .mlCompositionFailed:
                return "ml-composition-failed"
            case .motorwayCamera:
                return "motorway-camera"
            case .motorwayCameraPreview:
                return "motorway-camera-preview"
            case .motorwayCameraRotateDevice:
                return "motorway-camera-rotate-device"
            case .motorwayPhotosAppClipHome:
                return "motorway-photos-app-clip-home"
            case .motorwayPhotosAppClipWelcomeGuide:
                return "motorway-photos-app-clip-welcome-guide"
            case .viewVehicleDetailsSummaryTapped:
                return "view-vehicle-details-summary-tapped"
            case .confirmPhotoEditTapped:
                return "confirm-photo-edit-tapped"
            case .enterVrm:
                return "enter-vrm"
            case .confirmVehicle:
                return "confirm-vehicle"
            case .vrmSearch:
                return "vrm-search"
            case .vrmNotFound:
                return "vrm-not-found"
            case .vrmInvalid:
                return "vrm-invalid"
            case .vrmCheckFailed:
                return "vrm-check-failed"
            case .checkEligibilityFailed:
                return "check-eligibility-failed"
            case .estimateValuationFailed:
                return "estimate-valuation-failed"
            case .coreDataThreadViolation:
                return "coredata-thread-violation"
            case .vehicleHome:
                return "vehicle-home"
            case .confirmYourProfileClicked:
                return "confirm_your_profile_clicked"
            case .highMileage:
                return "high-mileage"
            case .mileageLessThanLastMOT:
                return "mileage-less-than-last-mot"
            case .valuationFetchFailed:
                return "valuation-fetch-failed"
            case .valuationFailed:
                return "valuation-failed"
            case .vehicleProfile:
                return "vehicle-profile"
            case .profileSummary:
                return "profile-summary"
            case .vehicleProfileSummaryConfirmTap:
                return "vehicle-profile-summary-confirm-tap"
            case .vehicleProfileLetsGetStarted:
                return "vehicle-profile-lets-get-started"
            case .vehicleProfileProofOfPurchaseQuestion:
                return "vehicle-profile-proof-of-purchase-question"
            case .vehicleProfileEquipmentQuestion:
                return "vehicle-profile-equipment-question"
            case .vehicleProfileSeatMaterialQuestion:
                return "vehicle-profile-seat-material-question"
            case .vehicleProfileNumberOfKeysQuestion:
                return "vehicle-profile-number-of-keys-question"
            case .vehicleProfileToolPackQuestion:
                return "vehicle-profile-tool-pack-question"
            case .vehicleProfileLockingWheelNutQuestion:
                return "vehicle-profile-locking-wheel-nut-question"
            case .vehicleProfileSmokingQuestion:
                return "vehicle-profile-smoking-question"
            case .vehicleProfileV5cLogbookQuestion:
                return "vehicle-profile-v5c-logbook-question"
            case .vehicleProfileLocationSearchQuestion:
                return "vehicle-profile-location-search-question"
            case .addressSuggestionsFailed:
                return  "address-suggestions-failed"
            case .addressDetailsFailed:
                return "address-details-failed"
            case .vehicleProfileLocationFormQuestion:
                return "vehicle-profile-location-form-question"
            case .updateSellerFailed:
                return "update-seller-failed"
            case .vehicleProfileOwnerQuestion:
                return "vehicle-profile-owner-question"
            case .vehicleProfileOwnerTypeQuestion:
                return "vehicle-profile-owner-type-question"
            case .vehicleProfileOwnerNameQuestion:
                return "vehicle-profile-owner-name-question"
            case .vehicleProfilePrivatePlateQuestion:
                return "vehicle-profile-private-plate-question"
            case .vehicleProfileKeepingThePlateQuestion:
                return "vehicle-profile-keeping-the-plate-question"
            case .vehicleProfileKeepPrivatePlateLinkTap:
                return "vehicle-profile-keep-private-plate-link-tap"
            case .vehicleProfileFinanceQuestion:
                return "vehicle-profile-finance-question"
            case .vehicleProfileBatteryOwnershipQuestion:
                return "vehicle-profile-battery-ownership-question"
            case .vehicleProfileChargingCablesQuestion:
                return "vehicle-profile-charging-cables-question"
            case .vehicleProfileProofOfPurchaseGuide:
                return "vehicle-profile-proof-of-purchase-guide"
            case .vehicleProfileNoProofOfPurchaseGuide:
                return "vehicle-profile-no-proof-of-purchase-guide"
            case .vehicleProfileProofOfPurchaseCallTap:
                return  "vehicle-profile-proof-of-purchase-call-tap"
            case .vehicleProfileV5cLogBookGuide:
                return "vehicle-profile-v5c-log-book-guide"
            case .vehicleProfileNoV5cLogbookGuide:
                return "vehicle-profile-no-v5c-logbook-guide"
            case .vehicleCriteriaNotMetGuideView:
                return "vehicle-criteria-not-met-guide-view"
            case .vehicleProfileConfirmCriteriaTap:
                return "vehicle-profile-confirm-criteria-tap"
            case .vehicleProfileV5CLogBookDVLALinkTap:
                return "vehicle-profile-v5c-log-book-dvla-link-tap"
            case .vehicleProfileSeatMaterialGuide:
                return "vehicle-profile-seat-material-guide"
            case .vehicleProfileToolPackGuide:
                return "vehicle-profile-tool-pack-guide"
            case .vehicleProfileLockingWheelNutGuide:
                return "vehicle-profile-locking-wheel-nut-guide"
            case .vehicleProfileChargingCablesGuide:
                return "vehicle-profile-charging-cables-guide"
            case .photoTips:
                return "photo-tips"
            case .deletePhoto:
                return  "delete-photo"
            case .photoCategoryExteriorTips:
                return "photo-category-exterior-tips"
            case .photoCategoryInteriorTips:
                return "photo-category-interior-tips"
            case .photoCategoryWheelTips:
                return "photo-category-wheel-tips"
            case .photoCategoryTyreTreadTips:
                return "photo-category-tyre-tread-tips"
            case .photoTipTakeGoodPhotos:
                return "photo-tip-take-good-photos"
            case .photoTipTidyAndClean:
                return "photo-tip-tidy-and-clean"
            case .photoTipGoodLighting:
                return "photo-tip-good-lighting"
            case .photoTipVehicleSpace:
                return "photo-tip-vehicle-space"
            case .photoRequirementsTips:
                return "photo-requirements-tips"
            case .vehicleCondition:
                return "vehicle-condition"
            case .takeMissingWheelPhotos:
                return "take-missing-wheel-photos"
            case .takeMissingTyrePhotos:
                return "take-missing-tyre-photos"
            case .conditionFailed:
                return "condition-failed"
            case .vehicleConditionCategory(let condition):
                return "vehicle-condition-category-\(condition)"
            case .vehicleConditionCategoryGallery(let photoType):
                return "vehicle-condition-category-gallery-\(photoType)"
            case .retryPhotoUpload:
                return "retry-photo-upload"
            case .vehicleConditionCategoryGalleryWheelDamage:
                return "vehicle-condition-category-gallery-wheel-damage"
            case .vehicleConditionCategoryGalleryTyreDamage:
                return "vehicle-condition-category-gallery-tyre-damage"
            case .vehicleConditionCategoryTyreDamage:
                return "vehicle-condition-category-tyre-damage"
            case .noWheelDamage:
                return "no-wheel-damage"
            case .noTyreDamage:
                return "no-tyre-damage"
            case .hasWheelDamage:
                return "has-wheel-damage"
            case .hasTyreDamage:
                return "has-tyre-damage"
            case .vehicleConditionScratchesScuffsGuide:
                return "vehicle-condition-scratches-scuffs-guide"
            case .vehicleConditionDentsGuide:
                return "vehicle-condition-dents-guide"
            case .vehicleConditionPaintworkProblemsGuide:
                return "vehicle-condition-paintwork-problems-guide"
            case .vehicleConditionWindscreenDamageGuide:
                return "vehicle-condition-windscreen-damage-guide"
            case .vehicleConditionWarningLightsGuide:
                return "vehicle-condition-warning-lights-guide"
            case .vehicleConditionWheelDamageGuide:
                return "vehicle-condition-wheel-damage-guide"
            case .vehicleConditionTyreDamageGuide:
                return "vehcile-condition-tyre-damage-guide"
            case .vehicleBodyDamageLocationChooser:
                return "vehicle-body-damage-location-chooser"
            case .vehicleServiceHistoryPhotos:
                return "vehicle-service-history-photos"
            case .photoPickerTapped:
                return "photo-picker-tapped"
            case .vehicleServiceHistoryInitialMenu:
                return "vehicle-service-history-initial-menu"
            case .updateServiceHistoryFailed:
                return "update-service-history-failed"
            case .tooManyVehicles:
                return "too-many-vehicles"
            case .removeVehicleFailed:
                return "remove-vehicle-failed"
            case .vehicleRemoved:
                return "vehicle-enquiry-removed"
            case .priceEstimateExplanation:
                return "price-estimate_explanation"
            case .priceEstimateExplanationCallTap:
                return "price-estimate-explanation-call-tap"
            case .whyHasMyPriceChangedPageCallButton:
                return "why_has_my_price_changed_page_call_button"
            case .whyHasMyPriceChangedPageLoaded:
                return "why_has_my_price_changed_page_loaded"
            case .confirmSheetView:
                return "confirm-sheet-view"
            case .confirmMyPricePageLoaded:
                return "confirm_my_price_page_loaded"
            case .confirmationModalPageLoaded:
                return "confirmation_modal_page_loaded"
            case .confirmProfile:
                return "confirm-profile"
            case .confirmMyPriceClicked:
                return "confirm_my_price_clicked"
            case .confirmProfileWithIncompleteVehicleDetails:
                return "confirm-profile-with-incomplete-vehicle-details"
            case .confirmProfileFailedToRefreshVehicleProfile:
                return "confirm-profile-failed-to-refresh-vehicle-profile"
            case .confirmProfileFailed:
                return "confirm-profile-failed"
            case .whyHasMyPriceChangedClicked:
                return "why_has_my_price_changed_clicked"
            case .confirmVehicleSummary:
                return "confirm-vehicle-summary"
            case .confirmEditVehicleProfileQuestion:
                return "confirm-edit-vehicle-profile-question"
            case .confirmEditDamagedWheels:
                return "confirm-edit-damaged-wheels"
            case .confirmEditDamagedTyres:
                return "confirm-edit-damaged-tyres"
            case .confirmEditDamageScratches:
                return "confirm-edit-damage-scratches"
            case .confirmEditDamageDents:
                return "confirm-edit-damage-dents"
            case .confirmEditDamagePaintwork:
                return "confirm-edit-damage-paintwork"
            case .confirmEditDamageMissingTrims:
                return "confirm-edit-damage-missing-trims"
            case .confirmEditDamageWindscreen:
                return "confirm-edit-damage-windscreen"
            case .confirmEditDamageWarningLights:
                return "confirm-edit-damage-warning-lights"
            case .confirmEditServiceHistory:
                return "confirm-edit-service-history"
            case .continueToConfirm:
                return "continue-to-confirm"
            case .getSellerPrepFailed:
                return "get-seller-prep-failed"
            case .getVehicleProfileFailed:
                return "get-vehicle-profile-failed"
            case .authenticationTokenIsEmptyOrNull:
                return "authentication-token-is-empty-or-null"
            case .authenticationResetToken:
                return "authentication-reset-token"
            case .requestVerificationCodeFailed:
                return "request-verification-code-failed"
            case .signInMobile:
                return "sign-in-mobile"
            case .signInByMobileCodeFailed:
                return "sign-in-by-mobile-code-failed"
            case .checkIdentityFailed:
                return "check-identity-failed"
            case .authenticateFailed:
                return "authenticate-failed"
            case .continueTapped:
                return "continue"
            case .startSelling:
                return "start-selling"
            case .startSellingFailed:
                return "start-selling-failed"
            case .signInMobileNumberNotFound:
                return "sign-in-mobile-number-not-found"
            case .signInResendVerificationCode:
                return "sign-in-resend-verification-code"
            case .signInEnterVerificationCode:
                return "sign-in-enter-verification-code"
            case .appClipSignInFailed:
                return "app-clip-sign-in-failed"
            case .accountDoesNotExist:
                return "account-does-not-exist"
            case .checkVerificationCodeFailed:
                return "check-verification-code-failed"
            case .checkVerificationCodeSuccess:
                return "check-verification-code-success"
            case .validMileageConfirmedEqualToEstimated:
                return "valid-mileage-confirmed-equal-to-estimated"
            case .validMileageConfirmedEqualToLastMOT:
                return "valid-mileage-confirmed-equal-to-last-mot"
            case .validMileageConfirmedEqualToEstimatedAndLastMOT:
                return "valid-mileage-confirmed-equal-to-estimated-and-last-mot"
            case .validMileageConfirmedLessThanEstimated:
                return "valid-mileage-confirmed-less-than-estimated"
            case .validMileageConfirmedGreaterThanEstimated:
                return "valid-mileage-confirmed-greater-than-estimated"
            case .validMileageEntered:
                return "valid-mileage-entered"
            case .ineligibleVehicle(let reason):
                return "ineligible-vehicle-\(reason)"
            case .enterFullName:
                return "enter-full-name"
            case .enterEmail:
                return "enter-email"
            case .enterMobileNumber:
                return "enter-mobile-number"
            case .phoneNumberUpdateNeeded:
                return "phone-number-update-needed"
            case .enterVerificationCode:
                return "enter-verification-code"
            case .valuationTooManyVehicles:
                return "valuation-too-many-vehicles"
            case .valuation:
                return "valuation"
            case .yourEstimatedPrice:
                return "your-estimated-price"
            case .profileCompleteCallTapped:
                return "profile-complete-call-tapped"
            case .nextSteps:
                return "next-steps"
            case .dateFormattingFailed:
                return "date-formatting-failed"
            case .deletePhotoTapped:
                return "delete_photo_tapped"
            case .viewPhotoAIAssistError:
                return "view_ai_assist_error"
            case .confirmVehicleWithAIAssistError:
                return "continue_with_ai_assist_error"
            case .vehiclePhotoCardTapped:
                return "vehicle_photo_card_tapped"
            case .photoUploadSuccess:
                return "photo-upload-success"
            case .photoUploadFailed:
                return "photo-upload-failed"
            case .selectedCameraDevice:
                return "selected-camera-device"
            case .editPhotoTapped:
                return "edit_photo_tapped"
            case .invalidUrl:
                return "invalid-url"
            case .remoteImageDownloadFailed:
                return "remote-image-download-failed"
            case .serviceHistoryCaptureTips:
                return "service-history-capture-tips"
            case .vehicleServiceHistory:
                return "vehicle-service-history"
            case .priceConfirmationTerms:
                return "price-confirmation_terms"
            case .vehiclePhotosCategory(let category):
                return "vehicle-photos-category-\(category)"
            case .serviceHistoryHelpDefinition:
                return "service-history-help-definition"
            case .vehiclePhotos:
                return "vehicle-photos"
            case .motorwayPhotosAppClipLoading:
                return "motorway-photos-app-clip-loading"
            case .findServiceHistoryHelp:
                return "find-service-history-help"
            case .noServiceHistory:
                return "no-service-history"
            case .vehicleList:
                return "vehicle-list"
            case .photoAIAssistPollingTimedOut:
                return "photo-ai-assist-polling-timed-out"
            case .remoteConfigFetchAndActivateFailed:
                return "remote-config-fetch-and-activate-failed"
            case .remoteConfigListeningFailed:
                return "remote-config-listening-failed"
            case .getPhotosFailed:
                return "get-photos-failed"
            case .updateVehicleProfileFailed:
                return "update-vehicle-profile-failed"
            case .updateDamageMetadataFailed:
                return "update-damage-metadata-failed"
            case .getEnquiryTimelineFailed:
                return "get-enquiry-timeline-failed"
            case .createEnquiryFailed:
                return "create-enquiry-failed"
            case .valuateEnquiryFailed:
                return "valuate-enquiry-failed"
            case .appClipUrl:
                return "app-clip-url"
            case .customDebug:
                return "custom-debug"
            case .malformedHTTPResponse:
                return "malformed-http-response"
            case .cachedPhotoMissing:
                return "cached-photo-missing"
            case .unableToLoadCachedImage:
                return "unable-to-load-cached-image"
            case .deletePhotoFailed:
                return "delete-photo-failed"
            case .photosToDownload:
                return "photos-to-download"
            case .photosDownloaded:
                return "photos-to-download"
            case .photoCorrectTapped:
                return "photo_correct_tapped"
            case .dynamicLinkProcessingFailed:
                return "dynamic-link-processing-failed"
            case .vehicleEngineCheckTipsTapped:
                return "vehicle-engine-check-tips-tapped"
            case .vehicleEngineCheckOpenTapped:
                return "vehicle-engine-check-open-tapped"
            case .vehicleEngineCheckSkipTapped:
                return "vehicle-engine-check-skip-tapped"
            case .vehicleEngineCheckCameraOpened:
                return "vehicle-engine-check-camera-opened"
            case .vehicleEngineCheckRetakeTapped:
                return "vehicle-engine-check-retake-tapped"
            case .vehicleEngineCheckUseVideoTapped:
                return "vehicle-engine-check-use-video-tapped"
            case .vehicleEngineCheckDeleteVideo:
                return "vehicle-engine-check-delete-video"
            case .vehicleEngineCheckCameraDismissed:
                return "vehicle-engine-check-camera-dismissed"
            case .noVehicleMatchingVrm:
                return "no-vehicle-matching-vrm-in-user-response"
            case .noDealerEnquiryId:
                return "no-dealer-enquiry-id"
            case .dealerEnquiryIdIsZero:
                return "api-response-dealer-enquiry-id-is-zero"
            case .enquiryProgressFailed:
                return "enquiry-progress-failed"
            case .fileDeletionError:
                return "file-deletion-error"
            case .userDetailsFailed:
                return "user-details-failed"
            case .s3UploadFailed:
                return "s3-upload-failed"
            case .s3UploadSuccess:
                return "s3-upload-success"
            case .noEnquiryId:
                return "no-enquiry-id"
            case .apiResponseMissingEnquiryObject:
                return "missing-expected-enquiry-object-from-vehicle"
            case .apiResponseMissingDealerObject:
                return "dealer-enquiry-id-is-missing-from-the-response"
            case .apiResponseDealerEnquiryIdIsZero:
                return "dealer-enquiry-id-is-zero-in-the-response"
            case .enquiryProgressOverall:
                return "enquiry-progress-overall"
            case .enquiryProgressVehicleProfile:
                return "enquiry-progress-vehicle-profile"
            case .enquiryProgressPhotosExterior:
                return "enquiry-progress-photos-exterior"
            case .enquiryProgressPhotosInterior:
                return "enquiry-progress-photos-interior"
            case .enquiryProgressPhotosWheels:
                return "enquiry-progress-photos-wheels"
            case .enquiryProgressPhotosTyres:
                return "enquiry-progress-photos-tyres"
            case .enquiryProgressCondition:
                return "enquiry-progress-condition"
            case .enquiryProgressServiceHistory:
                return "enquiry-progress-service-history"
            case .presignedUrlFailed:
                return "pre-signed-url-failed"
            case .getUserFailed:
                return "get-user-failed"
            }
        }
    }
}
// swiftlint:enable type_body_length
// swiftlint:enable file_length
